### ISSUE TITLE
psyplot runtime error

### ISSUE THREAD

**Issue by Try2Code** [Chilipp/psyplot#7]
Hi Philipp,
I installed the latest version via pip and typed ```psyplot -h``` getting this
```
% psyplot -h                                                                    [Tue 2018-09-18|16:02:13]
Traceback (most recent call last):
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 83, in safe_modulo
    return s % meta
ValueError: unsupported format character '%' (0x25) at index 188

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 83, in safe_modulo
    return s % meta
ValueError: unsupported format character '%' (0x25) at index 188

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ram/.local/bin/psyplot", line 7, in <module>
    from psyplot.__main__ import main
  File "/home/ram/.local/lib/python3.7/site-packages/psyplot/__init__.py", line 9, in <module>
    from psyplot.data import (
  File "/home/ram/.local/lib/python3.7/site-packages/psyplot/data.py", line 1503, in <module>
    class UGridDecoder(CFDecoder):
  File "/home/ram/.local/lib/python3.7/site-packages/psyplot/data.py", line 1539, in UGridDecoder
    @docstrings.dedent
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 398, in dedent
    doc = func.__doc__ and self.dedents(func.__doc__, stacklevel=4)
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 414, in dedents
    return safe_modulo(s, self.params, stacklevel=stacklevel)
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 98, in safe_modulo
    stacklevel=stacklevel)
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 105, in safe_modulo
    print_warning=print_warning, stacklevel=stacklevel)
  File "/home/ram/.local/lib/python3.7/site-packages/docrep/__init__.py", line 83, in safe_modulo
    return s % meta
ValueError: unsupported format character '%' (0x25) at index 188
<ram@melian:~/src/tmp/psyplot>
```

#### Output of ``psyplot -aV``

same output

is this due to python3.7?

**Comment by Chilipp** [comment]
Thank you very much! It was a typo in a docstring that is fixed by 52bdd0b361f0ca7d6f6a4947e9e7eb0983fed83c and apparently caused problems with python 3.7.

Could you install the latest dev branch and check, whether it works? I will make a new release by the end of this week.

**Comment by Try2Code** [comment]
sure, will check it tomorrow and msg you

**Comment by Try2Code** [comment]
With your dev branch it runs. 

```
[1] % psyplot -aV                                                                                                                                                                         [Tue 2018-09-18|21:46:16]
psy_reg.plugin:
  requirements:
    scipy: 1.1.0
    statsmodels: 0.9.0
  version: 1.1.0
psy_simple.plugin:
  version: 1.1.0
psyplot:
  requirements:
    matplotlib: 2.2.3
    numpy: 1.15.1
    pandas: 0.23.4
    python: 3.7.0 (default, Jul 15 2018, 10:44:58)  [GCC 8.1.1 20180531]
    xarray: 0.10.8
  version: 1.2.0
psyplot_gui:
  requirements:
    pyqt: 5.11.2
    qt: 5.11.1
    qtconsole: 4.4.1
  version: 1.1.0
```

but for creating a real plot I had to manually install (after installing psy-maps) xarray, dask and toolz. finally I could create my plots

```psyplot topo_r2b3.nc -n topo -pm mapplot -o r2b3.png```
![r2b3](https://user-images.githubusercontent.com/681390/45712805-c9284b00-bb7c-11e8-8e74-54030c07ed20.png)
```psyplot topo_r2b2.nc -n topo -pm mapplot -o r2b2.png```
![r2b2](https://user-images.githubusercontent.com/681390/45712806-c9284b00-bb7c-11e8-960c-1ec0dce6ca00.png)

input files area created with
```
cdo -f nc -topo,icoR2B2 topo_r2b2.nc 
cdo -f nc -topo,icoR2B3 topo_r2b3.nc
```

**Comment by Chilipp** [comment]
> but for creating a real plot I had to manually install (after installing psy-maps) xarray, dask and toolz.

yes, the conda-forge packages for python 3.7 are not yet existent but will hopefully come soon.
I close this issue but please reopen it, if you encounter any other problem with python 3.7
